import '../models/hasil_analisis.dart';

class AnalisisService {
  static final AnalisisService _instance = AnalisisService._internal();
  factory AnalisisService() => _instance;
  AnalisisService._internal();

  HasilAnalisis? analisis(String key) {
    return _db[key];
  }

  static List<Map<String, String>> daftarPilihan() {
    return [
      {'key': 'ikan_bandeng',  'label': 'Ikan Bandeng',     'emoji': '🐟', 'grup': 'Ikan dan Seafood'},
      {'key': 'ikan_kembung',  'label': 'Ikan Kembung',     'emoji': '🐠', 'grup': 'Ikan dan Seafood'},
      {'key': 'ikan_tongkol',  'label': 'Ikan Tongkol',     'emoji': '🎣', 'grup': 'Ikan dan Seafood'},
      {'key': 'ikan_kakap',    'label': 'Ikan Kakap Merah', 'emoji': '🐡', 'grup': 'Ikan dan Seafood'},
      {'key': 'udang_vaname',  'label': 'Udang Vaname',     'emoji': '🦐', 'grup': 'Ikan dan Seafood'},
      {'key': 'cumi_cumi',     'label': 'Cumi-Cumi',        'emoji': '🦑', 'grup': 'Ikan dan Seafood'},
      {'key': 'kepiting',      'label': 'Kepiting Bakau',   'emoji': '🦀', 'grup': 'Ikan dan Seafood'},
      {'key': 'kerang_hijau',  'label': 'Kerang Hijau',     'emoji': '🐚', 'grup': 'Ikan dan Seafood'},
      {'key': 'bayam',         'label': 'Bayam',            'emoji': '🥬', 'grup': 'Sayuran'},
      {'key': 'kangkung',      'label': 'Kangkung',         'emoji': '🌿', 'grup': 'Sayuran'},
      {'key': 'tomat',         'label': 'Tomat',            'emoji': '🍅', 'grup': 'Sayuran'},
      {'key': 'cabai_merah',   'label': 'Cabai Merah',      'emoji': '🌶', 'grup': 'Bumbu'},
      {'key': 'mangga',        'label': 'Mangga',           'emoji': '🥭', 'grup': 'Buah'},
      {'key': 'pisang',        'label': 'Pisang',           'emoji': '🍌', 'grup': 'Buah'},
    ];
  }

  static const Map<String, HasilAnalisis> _db = {
    'ikan_bandeng': HasilAnalisis(
      nama: 'Ikan Bandeng',
      namaIlmiah: 'Chanos chanos',
      jenis: 'Ikan Laut dan Payau',
      asal: 'Tambak Muara Angke, Jakarta',
      deskripsi: 'Bandeng adalah ikan air payau favorit masyarakat Indonesia. Dikenal dengan cita rasa gurih dan daging lembut. Banyak dibudidayakan di tambak Jawa dan Sulawesi.',
      skorKesegaran: 95,
      labelKesegaran: 'Sangat Segar',
      warnaLabel: 'hijau',
      nutrisiPer100g: {
        'Kalori': '129 kkal',
        'Protein': '20 g',
        'Lemak': '4.8 g',
        'Omega-3': '0.8 g',
        'Kalsium': '20 mg',
        'Zat Besi': '1.5 mg',
      },
      manfaatKesehatan: [
        'Tinggi protein untuk otot dan imunitas tubuh',
        'Omega-3 menjaga kesehatan jantung',
        'Baik untuk pertumbuhan tulang dan gigi',
        'Vitamin B12 mendukung fungsi saraf',
      ],
      tipsSimpan: [
        'Kulkas: maksimal 2 hari',
        'Freezer: tahan 3 bulan',
        'Bungkus plastik kedap udara sebelum simpan',
      ],
      caraOlah: [
        'Goreng bumbu kuning khas Jawa',
        'Pindang bandeng asam segar',
        'Bakar dengan kecap manis bawang',
        'Bandeng presto empuk tanpa duri',
      ],
      peringatan: [
        'Hati-hati duri kecil yang sangat banyak',
        'Penderita alergi ikan harap waspada',
      ],
      musimTerbaik: 'April sampai Oktober',
      hargaEstimasi: 'Rp 25.000 sampai Rp 40.000 per kg',
    ),

    'ikan_kembung': HasilAnalisis(
      nama: 'Ikan Kembung',
      namaIlmiah: 'Rastrelliger kanagurta',
      jenis: 'Ikan Laut',
      asal: 'Laut Jawa dan Selat Sunda',
      deskripsi: 'Kembung adalah ikan pelagis kecil yang melimpah di perairan Indonesia. Harga terjangkau tapi kandungan gizinya sangat tinggi. Sering disebut ikan rakyat.',
      skorKesegaran: 92,
      labelKesegaran: 'Sangat Segar',
      warnaLabel: 'hijau',
      nutrisiPer100g: {
        'Kalori': '103 kkal',
        'Protein': '22 g',
        'Lemak': '1.5 g',
        'Omega-3': '1.2 g',
        'DHA': '0.6 g',
        'Selenium': '45 mcg',
      },
      manfaatKesehatan: [
        'Omega-3 tertinggi di antara ikan murah',
        'DHA penting untuk kecerdasan otak anak',
        'Selenium kuat sebagai antioksidan',
        'Vitamin D untuk tulang kuat',
      ],
      tipsSimpan: [
        'Kulkas: maksimal 1 sampai 2 hari',
        'Freezer: tahan 2 bulan',
        'Pisahkan isi perut sebelum disimpan',
      ],
      caraOlah: [
        'Goreng crispy dengan tepung bumbu',
        'Kembung balado khas Minang',
        'Kuah kuning asam segar',
        'Bakar bumbu rica-rica',
      ],
      peringatan: [
        'Konsumsi segera karena mudah basi',
        'Hindari jika ada alergi histamin',
      ],
      musimTerbaik: 'Sepanjang tahun, terbanyak Maret sampai Mei',
      hargaEstimasi: 'Rp 18.000 sampai Rp 30.000 per kg',
    ),

    'ikan_tongkol': HasilAnalisis(
      nama: 'Ikan Tongkol',
      namaIlmiah: 'Euthynnus affinis',
      jenis: 'Ikan Laut',
      asal: 'Laut Jawa dan Samudra Hindia',
      deskripsi: 'Tongkol adalah ikan dari keluarga tuna. Dagingnya merah gelap, kaya protein dan zat besi. Populer di pasar tradisional karena harganya sangat terjangkau.',
      skorKesegaran: 88,
      labelKesegaran: 'Segar',
      warnaLabel: 'hijau',
      nutrisiPer100g: {
        'Kalori': '132 kkal',
        'Protein': '26 g',
        'Zat Besi': '3.2 mg',
        'Omega-3': '0.5 g',
        'Niasin': '12 mg',
        'Kalium': '444 mg',
      },
      manfaatKesehatan: [
        'Protein sangat tinggi untuk tenaga dan otot',
        'Zat besi tinggi untuk cegah anemia',
        'Sangat cocok untuk ibu hamil',
        'Kalium mengatur tekanan darah',
      ],
      tipsSimpan: [
        'Kulkas: 1 sampai 2 hari',
        'Freezer: tahan 3 bulan',
        'Bisa diawetkan menjadi ikan asin',
      ],
      caraOlah: [
        'Tongkol santan khas Jawa',
        'Abon tongkol pedas manis',
        'Oseng tongkol daun kemangi',
        'Pindang tongkol asam segar',
      ],
      peringatan: [
        'Histamin tinggi jika tidak segar bisa keracunan',
        'Pilih yang insangnya merah cerah dan mata jernih',
        'Jangan konsumsi jika bau asam tajam',
      ],
      musimTerbaik: 'Oktober sampai Februari',
      hargaEstimasi: 'Rp 20.000 sampai Rp 35.000 per kg',
    ),

    'ikan_kakap': HasilAnalisis(
      nama: 'Ikan Kakap Merah',
      namaIlmiah: 'Lutjanus campechanus',
      jenis: 'Ikan Laut Premium',
      asal: 'Perairan Dalam Laut Jawa dan Natuna',
      deskripsi: 'Kakap merah adalah ikan premium. Daging putih padat, sedikit duri, rasa mild dan disukai semua kalangan. Cocok untuk semua cara memasak.',
      skorKesegaran: 94,
      labelKesegaran: 'Sangat Segar',
      warnaLabel: 'hijau',
      nutrisiPer100g: {
        'Kalori': '128 kkal',
        'Protein': '26 g',
        'Lemak': '1.7 g',
        'Kalium': '522 mg',
        'Vitamin D': '14 mcg',
        'Niasin': '11 mg',
      },
      manfaatKesehatan: [
        'Protein sangat tinggi dan mudah dicerna',
        'Kalium tinggi untuk jantung yang sehat',
        'Rendah lemak dan aman untuk kolesterol',
        'Vitamin D untuk tulang kuat',
      ],
      tipsSimpan: [
        'Kulkas: 2 hari',
        'Freezer: tahan 4 bulan',
        'Lumuri jeruk nipis sebelum disimpan',
      ],
      caraOlah: [
        'Kakap kukus taosi khas Chinese',
        'Kakap bakar bumbu Bali',
        'Kakap asam manis saus tomat',
        'Sup kepala kakap segar',
      ],
      peringatan: [
        'Harga mahal, waspadai pemalsuan dengan ikan lain',
        'Penderita alergi ikan harap waspada',
      ],
      musimTerbaik: 'Mei sampai Agustus',
      hargaEstimasi: 'Rp 60.000 sampai Rp 100.000 per kg',
    ),

    'udang_vaname': HasilAnalisis(
      nama: 'Udang Vaname',
      namaIlmiah: 'Litopenaeus vannamei',
      jenis: 'Udang Budidaya',
      asal: 'Tambak Karawang, Jawa Barat',
      deskripsi: 'Udang vaname adalah jenis udang budidaya terpopuler di Indonesia. Rasanya manis, tekstur kenyal, dan mudah diolah dengan berbagai bumbu.',
      skorKesegaran: 98,
      labelKesegaran: 'Sangat Segar',
      warnaLabel: 'hijau',
      nutrisiPer100g: {
        'Kalori': '99 kkal',
        'Protein': '24 g',
        'Lemak': '0.3 g',
        'Yodium': '35 mcg',
        'Zinc': '1.1 mg',
        'Vitamin B3': '3.2 mg',
      },
      manfaatKesehatan: [
        'Protein sangat tinggi dengan lemak sangat rendah',
        'Yodium baik untuk fungsi tiroid',
        'Zinc meningkatkan daya tahan imunitas',
        'Rendah kalori cocok untuk diet sehat',
      ],
      tipsSimpan: [
        'Kulkas: 1 sampai 2 hari dalam wadah tertutup',
        'Freezer: tahan 3 sampai 4 bulan',
        'Simpan dengan es batu agar tetap segar',
      ],
      caraOlah: [
        'Udang saos tiram bawang putih',
        'Udang balado pedas manis',
        'Udang goreng tepung crispy',
        'Mie udang kuah santan',
      ],
      peringatan: [
        'ALERGI UDANG: hentikan makan dan segera ke dokter',
        'Masak sampai matang sempurna',
      ],
      musimTerbaik: 'Tersedia sepanjang tahun dari tambak',
      hargaEstimasi: 'Rp 60.000 sampai Rp 90.000 per kg',
    ),

    'cumi_cumi': HasilAnalisis(
      nama: 'Cumi-Cumi',
      namaIlmiah: 'Loligo edulis',
      jenis: 'Cephalopoda Laut',
      asal: 'Laut Jawa dan Selat Malaka',
      deskripsi: 'Cumi-cumi adalah moluska laut yang sangat digemari. Teksturnya kenyal dengan rasa gurih yang khas. Bisa diolah dengan berbagai cara memasak.',
      skorKesegaran: 90,
      labelKesegaran: 'Segar',
      warnaLabel: 'hijau',
      nutrisiPer100g: {
        'Kalori': '92 kkal',
        'Protein': '15.6 g',
        'Fosfor': '221 mg',
        'Selenium': '44 mcg',
        'Vitamin B12': '1.3 mcg',
        'Karbohidrat': '3.1 g',
      },
      manfaatKesehatan: [
        'Fosfor tinggi baik untuk tulang yang kuat',
        'Selenium kuat sebagai antioksidan alami',
        'Rendah lemak cocok untuk diet',
        'Vitamin B12 untuk energi dan fungsi saraf',
      ],
      tipsSimpan: [
        'Kulkas: konsumsi dalam 1 hari',
        'Freezer: tahan 2 bulan',
        'Bersihkan tinta dan tulang rawan terlebih dulu',
      ],
      caraOlah: [
        'Cumi hitam masak tintanya sendiri',
        'Cumi pedas manis khas Jawa',
        'Cumi goreng tepung crispy',
        'Semur cumi pedas santan',
      ],
      peringatan: [
        'Penderita alergi seafood harap waspada',
        'Masak sampai matang jangan setengah matang',
      ],
      musimTerbaik: 'Juni sampai September musim kemarau',
      hargaEstimasi: 'Rp 50.000 sampai Rp 80.000 per kg',
    ),

    'kepiting': HasilAnalisis(
      nama: 'Kepiting Bakau',
      namaIlmiah: 'Scylla serrata',
      jenis: 'Krustasea',
      asal: 'Hutan Bakau Muara Angke, Teluk Jakarta',
      deskripsi: 'Kepiting bakau adalah kepiting terbesar dan paling berdaging di Indonesia. Hidup di hutan mangrove. Dagingnya manis, gurih, dan sangat digemari.',
      skorKesegaran: 96,
      labelKesegaran: 'Sangat Segar',
      warnaLabel: 'hijau',
      nutrisiPer100g: {
        'Kalori': '87 kkal',
        'Protein': '18 g',
        'Zinc': '3.5 mg',
        'Selenium': '37 mcg',
        'Vitamin B12': '9.8 mcg',
        'Fosfor': '175 mg',
      },
      manfaatKesehatan: [
        'Zinc tinggi untuk sistem imun dan kesuburan',
        'Vitamin B12 tertinggi di antara semua seafood',
        'Selenium kuat sebagai anti kanker alami',
        'Rendah lemak dan kalori',
      ],
      tipsSimpan: [
        'Hidup: simpan di wadah basah dan konsumsi hari itu',
        'Matang: freezer tahan 1 bulan',
        'Masak segera setelah dibeli',
      ],
      caraOlah: [
        'Kepiting saus padang khas Sumatera',
        'Kepiting asam manis saus tomat',
        'Kepiting goreng mentega bawang putih',
        'Sop kepiting bening jahe sereh',
      ],
      peringatan: [
        'ALERGI SEAFOOD: sangat berisiko harap waspada',
        'Buang insang abu sebelum dimakan',
        'Beli yang masih hidup atau sangat segar',
      ],
      musimTerbaik: 'April sampai Juni dan September sampai November',
      hargaEstimasi: 'Rp 80.000 sampai Rp 150.000 per kg',
    ),

    'kerang_hijau': HasilAnalisis(
      nama: 'Kerang Hijau',
      namaIlmiah: 'Perna viridis',
      jenis: 'Moluska Laut',
      asal: 'Teluk Jakarta, Muara Angke',
      deskripsi: 'Kerang hijau banyak dibudidayakan di Teluk Jakarta. Harganya sangat murah tetapi kandungan gizinya sangat tinggi terutama mineral dan vitamin.',
      skorKesegaran: 85,
      labelKesegaran: 'Segar',
      warnaLabel: 'kuning',
      nutrisiPer100g: {
        'Kalori': '86 kkal',
        'Protein': '11.9 g',
        'Zat Besi': '6.7 mg',
        'Zinc': '2.7 mg',
        'Vitamin B12': '12 mcg',
        'Omega-3': '0.5 g',
      },
      manfaatKesehatan: [
        'Zat besi sangat tinggi untuk cegah anemia',
        'Vitamin B12 terbaik untuk kesehatan saraf',
        'Omega-3 baik untuk jantung sehat',
        'Harga murah dengan gizi yang tinggi',
      ],
      tipsSimpan: [
        'Simpan dalam wadah berisi air garam',
        'Konsumsi hari itu juga jangan ditunda',
        'Buang cangkang yang sudah terbuka sebelum masak',
      ],
      caraOlah: [
        'Kerang hijau saus tiram pedas',
        'Tumis kerang bawang putih jahe',
        'Kerang bakar kecap manis',
        'Mie kerang kuah kaldu segar',
      ],
      peringatan: [
        'Teluk Jakarta tercemar sehingga masak SANGAT matang',
        'Ibu hamil sebaiknya hindari',
        'Buang kerang yang cangkangnya sudah terbuka',
      ],
      musimTerbaik: 'Tersedia sepanjang tahun',
      hargaEstimasi: 'Rp 8.000 sampai Rp 15.000 per kg',
    ),

    'bayam': HasilAnalisis(
      nama: 'Bayam',
      namaIlmiah: 'Amaranthus tricolor',
      jenis: 'Sayuran Daun',
      asal: 'Kebun Jawa Barat dan Jawa Tengah',
      deskripsi: 'Bayam adalah sayuran daun hijau yang sangat populer di Indonesia. Kaya zat besi dan vitamin. Mudah ditanam dan tersedia sepanjang tahun di seluruh pasar.',
      skorKesegaran: 90,
      labelKesegaran: 'Segar',
      warnaLabel: 'hijau',
      nutrisiPer100g: {
        'Kalori': '23 kkal',
        'Protein': '2.9 g',
        'Zat Besi': '3.5 mg',
        'Vitamin A': '469 mcg',
        'Vitamin C': '28 mg',
        'Kalsium': '99 mg',
      },
      manfaatKesehatan: [
        'Zat besi tinggi untuk cegah dan atasi anemia',
        'Vitamin A baik untuk mata dan kulit sehat',
        'Kalsium untuk tulang dan gigi kuat',
        'Sangat baik untuk ibu hamil dan menyusui',
      ],
      tipsSimpan: [
        'Kulkas: tahan 2 sampai 3 hari',
        'Bungkus kain lembab agar tetap segar',
        'Jangan dicuci sebelum disimpan karena cepat busuk',
      ],
      caraOlah: [
        'Sayur bening bayam wortel',
        'Tumis bayam bawang putih',
        'Cah bayam telur',
        'Bayam dalam sop atau mie',
      ],
      peringatan: [
        'Penderita batu ginjal batasi konsumsi karena oxalat tinggi',
        'Penderita asam urat jangan berlebihan',
      ],
      musimTerbaik: 'Sepanjang tahun',
      hargaEstimasi: 'Rp 3.000 sampai Rp 8.000 per ikat',
    ),

    'kangkung': HasilAnalisis(
      nama: 'Kangkung',
      namaIlmiah: 'Ipomoea aquatica',
      jenis: 'Sayuran Daun',
      asal: 'Kebun Air Seluruh Indonesia',
      deskripsi: 'Kangkung adalah sayuran daun yang paling mudah tumbuh di Indonesia. Bisa tumbuh di air maupun di tanah. Rasanya lembut dan sangat mudah diolah.',
      skorKesegaran: 92,
      labelKesegaran: 'Sangat Segar',
      warnaLabel: 'hijau',
      nutrisiPer100g: {
        'Kalori': '19 kkal',
        'Protein': '2.6 g',
        'Vitamin A': '315 mcg',
        'Vitamin C': '55 mg',
        'Zat Besi': '1.7 mg',
        'Kalsium': '77 mg',
      },
      manfaatKesehatan: [
        'Vitamin C sangat tinggi untuk imunitas yang kuat',
        'Vitamin A baik untuk kesehatan mata',
        'Antioksidan alami pencegah penyakit',
        'Sangat rendah kalori cocok untuk semua usia',
      ],
      tipsSimpan: [
        'Rendam pangkal batang di dalam air',
        'Kulkas: tahan 2 sampai 3 hari',
        'Pilih yang daunnya masih hijau cerah',
      ],
      caraOlah: [
        'Cah kangkung belacan pedas',
        'Tumis kangkung bawang merah',
        'Kangkung dalam sayur lodeh',
        'Kangkung goreng bumbu terasi',
      ],
      peringatan: [
        'Cuci bersih karena sering tumbuh di air yang kotor',
      ],
      musimTerbaik: 'Sepanjang tahun',
      hargaEstimasi: 'Rp 2.000 sampai Rp 5.000 per ikat',
    ),

    'tomat': HasilAnalisis(
      nama: 'Tomat',
      namaIlmiah: 'Solanum lycopersicum',
      jenis: 'Sayuran Buah',
      asal: 'Kebun Malang, Jawa Timur',
      deskripsi: 'Tomat adalah buah yang dipakai sebagai sayuran dalam masakan. Kaya likopen dan vitamin C. Salah satu bahan masak terpenting di seluruh Indonesia.',
      skorKesegaran: 93,
      labelKesegaran: 'Sangat Segar',
      warnaLabel: 'hijau',
      nutrisiPer100g: {
        'Kalori': '18 kkal',
        'Vitamin C': '23 mg',
        'Likopen': '3.7 mg',
        'Vitamin A': '42 mcg',
        'Kalium': '237 mg',
        'Folat': '15 mcg',
      },
      manfaatKesehatan: [
        'Likopen kuat sebagai anti kanker alami',
        'Vitamin C tinggi untuk imunitas dan kulit',
        'Baik untuk kesehatan jantung dan pembuluh darah',
        'Sangat rendah kalori baik untuk semua',
      ],
      tipsSimpan: [
        'Simpan di suhu ruang bukan di kulkas',
        'Pisahkan yang sudah matang dan yang belum',
        'Jangan simpan dalam plastik tertutup rapat',
      ],
      caraOlah: [
        'Sambal tomat segar',
        'Saus tomat untuk berbagai masakan',
        'Lalapan mentah segar',
        'Tumis tomat telur',
      ],
      peringatan: [
        'Penderita asam urat batasi konsumsi',
      ],
      musimTerbaik: 'Sepanjang tahun terbaik di musim kemarau',
      hargaEstimasi: 'Rp 5.000 sampai Rp 15.000 per kg',
    ),

    'cabai_merah': HasilAnalisis(
      nama: 'Cabai Merah',
      namaIlmiah: 'Capsicum annuum',
      jenis: 'Bumbu dan Rempah',
      asal: 'Kebun Jawa Tengah dan Jawa Timur',
      deskripsi: 'Cabai merah adalah bumbu wajib hampir semua masakan Indonesia. Kandungan capsaicin memberi rasa pedas dan sekaligus banyak manfaat kesehatan.',
      skorKesegaran: 91,
      labelKesegaran: 'Segar',
      warnaLabel: 'hijau',
      nutrisiPer100g: {
        'Kalori': '40 kkal',
        'Vitamin C': '143 mg',
        'Vitamin A': '952 mcg',
        'Capsaicin': 'Sangat Tinggi',
        'Kalium': '322 mg',
        'Vitamin B6': '0.5 mg',
      },
      manfaatKesehatan: [
        'Vitamin C sangat tinggi untuk imunitas yang kuat',
        'Capsaicin membakar lemak dan tingkatkan metabolisme',
        'Anti-inflamasi alami yang kuat',
        'Vitamin A sangat baik untuk kesehatan mata',
      ],
      tipsSimpan: [
        'Suhu ruang: tahan sekitar 1 minggu',
        'Kulkas: tahan 2 sampai 3 minggu',
        'Freezer: tahan 6 bulan setelah diblansir',
      ],
      caraOlah: [
        'Sambal ulek berbagai varian',
        'Bumbu balado khas Minang',
        'Bumbu dasar merah masakan Indonesia',
        'Oseng-oseng berbagai sayur dan lauk',
      ],
      peringatan: [
        'Penderita maag dan lambung hindari berlebihan',
        'Cuci tangan setelah pegang dan jangan sentuh mata',
      ],
      musimTerbaik: 'Sepanjang tahun harga sangat fluktuatif',
      hargaEstimasi: 'Rp 20.000 sampai Rp 80.000 per kg',
    ),

    'mangga': HasilAnalisis(
      nama: 'Mangga',
      namaIlmiah: 'Mangifera indica',
      jenis: 'Buah Tropis',
      asal: 'Kebun Probolinggo, Jawa Timur',
      deskripsi: 'Mangga adalah buah tropis raja rasa dari Indonesia. Tersedia banyak varietas seperti harum manis, gedong gincu, dan manalagi.',
      skorKesegaran: 94,
      labelKesegaran: 'Sangat Segar',
      warnaLabel: 'hijau',
      nutrisiPer100g: {
        'Kalori': '60 kkal',
        'Vitamin C': '36 mg',
        'Vitamin A': '54 mcg',
        'Folat': '43 mcg',
        'Kalium': '168 mg',
        'Serat': '1.6 g',
      },
      manfaatKesehatan: [
        'Vitamin C tinggi untuk imunitas dan kulit cerah',
        'Folat sangat penting untuk ibu hamil',
        'Serat baik untuk pencernaan yang lancar',
        'Antioksidan kuat mencegah penuaan dini',
      ],
      tipsSimpan: [
        'Belum matang: simpan di suhu ruang',
        'Sudah matang: kulkas tahan 3 sampai 5 hari',
        'Dikupas dan dipotong: freezer tahan 6 bulan',
      ],
      caraOlah: [
        'Jus mangga segar tanpa gula',
        'Rujak buah asam manis pedas',
        'Dimakan langsung saat segar',
        'Es krim atau es mangga',
      ],
      peringatan: [
        'Penderita diabetes batasi konsumsi karena gula tinggi',
        'Sebagian orang alergi terhadap getah kulit mangga',
      ],
      musimTerbaik: 'Oktober sampai Januari',
      hargaEstimasi: 'Rp 10.000 sampai Rp 30.000 per kg',
    ),

    'pisang': HasilAnalisis(
      nama: 'Pisang',
      namaIlmiah: 'Musa paradisiaca',
      jenis: 'Buah Tropis',
      asal: 'Kebun Seluruh Nusantara',
      deskripsi: 'Pisang adalah buah paling mudah dijangkau di seluruh Indonesia. Tersedia sepanjang tahun, bergizi tinggi, dan cocok untuk semua usia dari bayi hingga lansia.',
      skorKesegaran: 96,
      labelKesegaran: 'Sangat Segar',
      warnaLabel: 'hijau',
      nutrisiPer100g: {
        'Kalori': '89 kkal',
        'Kalium': '358 mg',
        'Vitamin B6': '0.4 mg',
        'Vitamin C': '8.7 mg',
        'Serat': '2.6 g',
        'Magnesium': '27 mg',
      },
      manfaatKesehatan: [
        'Kalium tertinggi untuk jantung dan otot yang sehat',
        'Energi cepat cocok dimakan sebelum olahraga',
        'Serat baik untuk pencernaan yang lancar',
        'Aman untuk bayi, lansia, dan ibu hamil',
      ],
      tipsSimpan: [
        'Simpan di suhu ruang jangan masukkan kulkas',
        'Pisahkan dari buah lain karena gas etilen',
        'Dikupas lalu beku di freezer tahan 3 bulan',
      ],
      caraOlah: [
        'Dimakan langsung saat segar',
        'Pisang goreng crispy',
        'Smoothie pisang dan susu',
        'Kue pisang kukus atau bolu pisang',
      ],
      peringatan: [
        'Penderita gagal ginjal harus batasi konsumsi kalium',
        'Pisang sangat matang kadar gulanya lebih tinggi',
      ],
      musimTerbaik: 'Tersedia sepanjang tahun di seluruh Indonesia',
      hargaEstimasi: 'Rp 5.000 sampai Rp 20.000 per sisir',
    ),
  };
}
